import { useState } from 'react';
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

const PrivacyPolicy = () => {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" className="text-gray-600 hover:text-gray-800">
          Privacy Policy
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold mb-4">Privacy Policy</DialogTitle>
        </DialogHeader>
        <div className="prose prose-sm max-w-none">
          {/* Add your privacy policy content here */}
          <h2> Privacy Policy of SHIKSHAN AI Application</h2>
          {`
            Date: 01 May 2025
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            SHIKSHAN AI (Digital Infrastructure for Knowledge Sharing) is the Platform for School Education for the benefit of parents, teachers and learners across the globe. SHIKSHAN AI is the initiative of Justech AI Innovations LLP. Users of SHIKSHAN AI can access content for learning on the SHIKSHAN AI mobile application.
            The privacy and protection of data of SHIKSHAN AI’s Users is of utmost importance and shall be ensured at all times. This Privacy Policy shall cover details of data protection and management on SHIKSHAN AI, including how personal data of users of SHIKSHAN AI is managed, used and processed. Users are individuals who access and use SHIKSHAN AI and broadly comprise (i) users who access and use SHIKSHAN AI after registering themselves on SHIKSHAN AI also referred as Registered Users (iii) Content Builder Users are the users who are registered on SHIKSHAN AI and are authorised to be content creators, administrators on behalf of Institutional Users (such as State Education Departments, Zila Parishad etc.). More details on the rights and responsibilities of Users are set out in the Terms of Use.
            By accessing and using SHIKSHAN AI, and by providing your information on SHIKSHAN AI, you consent to the collection and use of the information you disclose on SHIKSHAN AI by VOPA and relevant Administrators of SHIKSHAN AI in accordance with the policies and guidelines of SHIKSHAN AI as applicable from time to time, including the Terms of Use and this Privacy Policy. If you do not agree with the contents of this policy, please do not access or use SHIKSHAN AI.
            Interpretation and Definitions
            Interpretation
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            Definitions
            For the purposes of this Privacy Policy:
            Account means a unique account created for You to access our Service or parts of our Service.
            Affiliate means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            Application means the software program provided by the Company downloaded by You on any electronic device, named SHIKSHAN AI also referred as SHIKSHAN AI or SHIKSHAN AI by Justech AI Innovations LLP. 
            Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Justech AI Innovations LLP, S No. 54/1/A/1, Vanity Homes, Flat No 202, Bavdhan, Chaturshringi Police Station, Haveli, Pune- 411021, Maharashtra, India
            Country refers to: Maharashtra, India
            Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.
            Personal Data is any information that relates to an identified or identifiable individual.
            Service refers to the Application.
            Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            You, means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            User means an adult person typically a teacher or parent or any other adult who has downloaded SHIKSHAN AI Application on his/her digital device used to complete the registration on SHIKSHAN AI by providing basic information like mobile number, email address, and self declared income category, and caste category.
            Learner User Profile means a profile created by the user for himself/herself/ for children/students in order to access the services by the application. It requires information like name, class, medium, school, district, and block information.
            Administrator or Admin means the technical, non technical admin profiles, content builder users, who have access to the web app of the SHIKSHAN AI Application.
            Content Builder User means the adult individual users who can create educational content for SHIKSHAN AI Application. They are the teachers, volunteers, subject experts etc.
            This Privacy Policy should be read in conjunction with the Terms of Use. Defined terms used but not defined herein shall have the meaning ascribed to them in the Terms of Use.
            Rights of Users:
            Right to fair, transparent and lawful collection of your data and information on SHIKSHAN AI
            Right to be informed about the ways in which your data and information that is collected on SHIKSHAN AI will be used
            Right to receive all the information you need to provide informed consent before collection of your personally identifiable information or sensitive personal data or information on SHIKSHAN AI and sharing of the same with relevant Administrators
            Right to revoke such consent
            Right to privacy and confidentiality regarding your personal data and information
            Right to proper use of your personal data and information by Administrators for specified and legitimate purposes related to your use of SHIKSHAN AI
            Right to keep your personal information accurate and up to date
            Right to secure collection, handling and storage of your personal data and information
            Right to protection from unauthorised or unlawful use of your personal data and information
            Right to view and access SHIKSHAN AI’s privacy policy
            Responsibilities of Administrators with respect to User data and information
            To respect the privacy and data protection rights of Users
            To ensure the security of and use of data (especially any personal information) shared by Registered Users is limited solely to the uses and purposes mentioned here
            To know that any use of data for purposes outside of the proper use shall be considered violation of the terms of the policies of SHIKSHAN AI as well as applicable laws and policies of India and they shall be responsible and liable for such actions and for any loss or damage arising from failure to comply with this obligation
            To ensure their communication (if any) with Registered Users is explicitly limited and relevant to the purpose of their usage of SHIKSHAN AI and meets the Appropriateness standards set out in the Content Policy of SHIKSHAN AI
            To ensure that their Content and programs on SHIKSHAN AI are not used for any of the Prohibited Uses set out in the Terms of Use
            What User data and information is collected on SHIKSHAN AI?
            All Users (Adult registered individuals) can expect the following data and information of theirs to be collected on SHIKSHAN AI:
            Basic Information: User Type (e.g. Parent, teacher etc.)
            Email Address,
            Mobile number
            Caste category
            Income category
            The caste and income data is collected in order to build aggregated average use data to ensure if the SHIKSHAN AI application at large is really benefiting the underserved Users from backward sections of the societies. The email or mobile number is collected to ensure registering a unique User.
            SHIKSHAN AI Usage: Usage history, time spent on Content, Content created/ contributed / published and its usage, progress in trackable collections of Content (e.g. courses), scores & assessment results, question-wise answers and other telemetry data in relation to usage of SHIKSHAN AI, badges generated, certificates issued.
            IP Address: Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            In case where a User creates Learner User Profile, the following additional information of their choice maybe collected on SHIKSHAN AI:
            Name and Surname
            Gender
            State
            District
            Block
            School name / U-DISE
            Learning Preferences: Board of interest, Medium of instruction, Classes of interest, Subjects of interest
            No other personally identifiable information or sensitive personal data or information of the User is collected. Following data is not asked for or collected by SHIKSHAN AI.
            Personal identity: identifying individuals through government-issued numbers.
            National identification number (for example Aadhar, passport number, PAN etc. are never asked.
            Government IDs of law enforcement, military or security personnel.
            Personal information: directly identifying an individual, by indicating the ID number or registration information and the individual’s name.
            Records or official documentation of civil registry information (marriage, birth, death, name change or gender recognition and so on).
            Immigration and work status documents
            Driving licences or licence plates, etc.
            Credit card/debit card etc.
            Digital identity: authenticating access to an online identity. E.g. Email addresses with passwords. Digital identities with passwords. Passwords, pins or codes to access private information.
            All Users (using the SHIKSHAN AI mobile app to access SHIKSHAN AI) have to create a Learner User Profile which specifies the User type, Geographical Information and learning Preferences. They may choose to customise their profile by changing these details at any time as well as providing their name. Only Registered Users can view their profile on SHIKSHAN AI mobile app, and their profiles specify all the additional information provided by such a Registered User.
            Children’s Privacy: SHIKSHAN AI prompts the owner of digital device i.e. the User to provide the email address or mobile number as a proof of being a teacher/ parent / guardian for the purposes of unique registration. Children under 18 years of age are neither required to nor encouraged to register on their own or provide their unique personal information. We do not knowingly collect personally identifiable unique information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Unique Personal Data, please contact Us. If We become aware that we have collected Personal Data from anyone under the age of 18 without verification of parental unique registration or consent of parent/guardian, We take steps to remove that information from Our servers.
            You represent to us that the data and information you provide on SHIKSHAN AI from time to time is and shall be correct, current and updated and you have all the rights, permissions and consents to provide such data and information. Your providing the information or data and the consequent storage, collection, usage, transfer, access or processing of the same in accordance with the Terms of Use and this Privacy Policy shall not be in violation of any third party agreement, laws, charter documents, judgments, orders and decrees.
            How is User data and information collected?
            Basic Information, Geographical Information and Preferences maybe collected when a User accesses and uses SHIKSHAN AI. These details can be updated by the User from their profile.
            Usage data of Users is collected as and when a User accesses, uses and navigates SHIKSHAN AI through different profiles.
            The additional information provided by Registered Users, is collected when a User creates a Learner User Profile on SHIKSHAN AI or when a Registered User updates their profile.
            Declared Information of Registered Users is collected with their explicit consent when they choose to provide the same on SHIKSHAN AI, through their registration or otherwise.
            Who has access to User data and information?
            SHIKSHAN AI Usage data (including Usage across the States and Districts) is a part of anonymised and aggregated data sets that is accessible to relevant Administrators of SHIKSHAN AI and to the employees, contractors or subcontractors of the technology service providers of SHIKSHAN AI.
            If you are a User, your Basic Information, Geographical Information, Preferences, and Usage data is accessible to the employees, contractors or subcontractors of the technology service providers of SHIKSHAN AI (under strict confidentiality obligations) if they need to access the data to process it on behalf of SHIKSHAN AI or an Administrator or to provide the services available on SHIKSHAN AI. For Registered Users, your Name is also accessible in this manner.
            If you are a User, your Learner User Profile data is accessible to other Users as a part of various functions and services of SHIKSHAN AI. i.e. Usage in time, performance data, name, surname, class, are accessible to other Users of the Application as a part of essential information to provide various functions and services. E.g. Leaderboard, My School etc.
            Registered Users also have an option to explicitly consent to give relevant Administrators access to their Name, Basic Information, Preferences, Usage data, and Declared Information for specified purposes such as implementation of programs on SHIKSHAN AI like courses.
            Usage data of Learner User Profiles categorized according to State, District, block and school could be also available publicly on SHIKSHAN AI.
            Personal data of Users is not shared with other Users using SHIKSHAN AI Application. E.g. Phone number, email, Caste, income etc. is not shared with other Users.
            In order to provide and improve SHIKSHAN AI, a limited number of third-party services require access to some of your personal data and information, eg. PlayStore, AppStore. Third party services are contractually prohibited from using your information except to provide the service.
            Your data and information is only accessible outside of the SHIKSHAN AI platform when it is necessary to offer the service, comply with law, or with your permission.
            What is User data and information used for?
            SHIKSHAN AI processes your data and information when necessary for providing access to Content for educational purposes and running programs on SHIKSHAN AI. These purposes are legitimate. The uses of your data are set out below:
            To create a profile for you to have a customized experience on SHIKSHAN AI,
            To suggest relevant Content for you to conveniently discover Content based on your preferences, activities on SHIKSHAN AI, and Content you are viewing on SHIKSHAN AI;
            To enable you to access and use Content on SHIKSHAN AI;
            To enable you to participate in programs run by VOPA, and Partner entities.
            To provide you push notifications on your hand-held devices
            To track your progress in collections of Content for which progress is tracked / recorded such as chapters, courses etc.
            To generate badges for or issue certificates to you upon completion of milestones;
            To maintain records of your progress and certificates/badges in relation to collections of Content you have accessed and used;
            To measure interest in the offerings on SHIKSHAN AI and to improve SHIKSHAN AI over time;
            To track and analyse usage of Content on SHIKSHAN AI by Administrators and Content providers to improve SHIKSHAN AI and its offerings over time;
            To assess, evaluate, validate Content submitted / posted / uploaded by Content building Users;
            To report anonymised usage of SHIKSHAN AI and its Content by Administrators to improve SHIKSHAN AI over time;
            To contact you and deliver information, administrative notices, seek feedback or other communications in connection with your usage of SHIKSHAN AI. By accepting the Terms of Use including the Privacy Policy, you expressly agree to receive this information;
            To suggest details for your profile such as your declared State and District;
            To resolve disputes, troubleshoot problems, detect and protect you against fraud and other criminal activity, enforce the Terms of Use and any other agreements;
            At times multiple users may be looked at to identify problems or resolve disputes, and in particular may examine your information or data to identify users using multiple User IDs or aliases. Your information or data may be compared or reviewed for errors, omissions and for accuracy; and
            For any other use that may be described to you at the time of collection.
            The administrators and technology support providers of SHIKSHAN AI may use third parties as service providers to facilitate or outsource one or more aspects of service operations that are provided on SHIKSHAN AI (e.g., search technology, discussion boards, technical service providers, affiliate) and therefore some of your information or data may be provided directly to these service providers. These service providers are subject to confidentiality and other legal restrictions that prohibit their use of the information provided to them for any purpose other than to facilitate specific website related operations.
            If we wish to use your data and information for a new purpose, not covered by this Privacy Policy, then we will provide you with a new notice explaining this new use prior to commencing the processing and setting out the relevant purposes and processing conditions. Where and whenever necessary, we will seek your prior consent to the new processing, unless authorized by law.
            In any event, your data will not be used for any of the following purposes:
            Rent or sale or other commercial purposes
            Advertising or marketing
            Phone calls or other forms of unsolicited communication that is not related to your usage of SHIKSHAN AI;
            Building a personal profile, other than for educational purposes on SHIKSHAN AI;
            Any of the Prohibited Purposes set out in the Terms of Use; and
            Any purpose that is not disclosed in this policy or on SHIKSHAN AI.
            Administrators are responsible for any use of data and information outside the proper use and shall be held accountable for the violation of the terms and policies of SHIKSHAN AI, as well as applicable laws and policies of India for any misuse. Administrators shall be liable for such actions and for any loss or damage arising from failure to comply with the obligation of proper use of your data and information. Should you believe that your data or information is being used in a manner inconsistent with this Privacy Policy, please contact the SHIKSHAN AI support team with the details of your concern by sending an email to contact.justechai@gmail.com 
            As a User, you understand, agree and acknowledge that the collection, storage and processing of your information or data on SHIKSHAN AI is for a lawful purpose connected with a function or activity of SHIKSHAN AI. You further understand, agree and acknowledge that your information or data which is classified as personal information as per applicable laws is considered necessary for us to provide various services on and in relation to SHIKSHAN AI to you and for your usage of SHIKSHAN AI.
            How is User data and information stored?
            Reasonable and appropriate security practices and procedures are being adopted to secure your personal data and information in accordance with Indian laws currently in force, including the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011. These measures include administrative, physical security, and technical controls in order to safeguard your personal data and information.
            Your data, including your Declared Information, any personally identifiable information or sensitive personal data or information is securely stored using cloud services which have it’s servers in India. Your data and information will primarily be stored in electronic form however certain data may also be stored in physical form.
            Third party service providers are engaged to store and process your data. These service providers are contractually bound to follow reasonable security standards to safeguard your data.
            Your email address and mobile number and any other personally identifiable information is only collected should you choose to provide the same and it is encrypted and stored securely. Personally identifiable information is only shared with Administrators for purposes specified to you, with your explicit consent and under the obligation that the Administrators will use such information only in connection with your usage of SHIKSHAN AI.
            Your IP address is only collected once for the limited purpose of ascertaining and suggesting your State and District. Your IP address is not stored on SHIKSHAN AI at any time.
            Additionally, a variety of methods such as network and infrastructure security, encryption and manual security procedures are used to secure your information and data against loss or damage and to help protect the accuracy and security of your personal information / general information / usage data and to prevent unauthorized access or improper use. If you think that SHIKSHAN AI or any of your personal information / general information / usage data is not secure or that there has been unauthorized access to the website or your personal data, please contact  at contact.justechai@gmail.com 
            Although SHIKSHAN AI strives to protect your personal information and data, it cannot guarantee the security of your data while it is being transmitted to its site; any transmission is at your own risk. Once your information has been received, reasonable procedures and security features are in place to reasonably endeavor to prevent unauthorized access in accordance with Indian law.
            How long is User data and information stored?
            Your data will not be retained for a period more than necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required by law or for directly related legitimate purposes.
            What are the system permissions required by the SHIKSHAN AI?
            Microphone – If you are a Content Builder User, your system Microphone will be used if voice recording is explicitly required by you as part of a Content for the purposes of education. Your system Microphone will be used if a Content Builder User creating Content wants to add a voice recording to Content. This voice recording will become part of the Content.
            Camera – Your system Camera will only be used if you choose to use it to capture a photo as a profile picture.
            Access to file manager / files – This is used by the SHIKSHAN AI android / iOS applications (as may be applicable) to transfer Content to an external storage space.
            Cookies: How are they used? What types of cookies are used? How to manage your cookies?
            Out of all the consumption clients, only the SHIKSHAN AI web portal uses cookies. SHIKSHAN AI only uses session cookies, none of the other types of cookies. SHIKSHAN AI session cookies are used to store URLs in order to better redirect users to the right pages. This is to enable faster loading of the pages the User interacts with. No personal information, or user preferences are stored in cookies.
            Users can clear their cookies by going to their browser settings and clearing their browsing data (by specifically checking off the option to clear cookies). Doing so, does not impact their user experience on SHIKSHAN AI as usage of SHIKSHAN AI sets the cookies again. Users can also choose to block cookies from the settings as well. Doing so, will mean that certain things on SHIKSHAN AI will not function properly. For eg., images/plugins may take a long time to load and the user will not be taken to the right pages after login.
            Data and information SHIKSHAN AI is not responsible for
            SHIKSHAN AI may have Content, webpages, cookies, files, software, data or other information or communication links that are originated, created or posted by third parties that may have the capability to collect, store or use your data or information. The administrators and technology support providers of SHIKSHAN AI are not responsible for such data or information collected, stored or used by third parties even if such third parties use SHIKSHAN AI to collect, store or use such data or information.
            If you access SHIKSHAN AI through a third party QR code scanner, App or through a web browser, the administrators and technology support providers of SHIKSHAN AI are not responsible for the data or information collected by such third parties.
            SHIKSHAN AI is not responsible for the privacy practices of other websites and users need to be aware of the data privacy practices of such sites should they choose to use these links.
            Compliance with laws and law enforcement
            The administrators and technology support providers of SHIKSHAN AI cooperate with governments and law enforcement agencies or any third party by any order under law for the time being in force to enforce and comply with the law. Any information about you will be disclosed to the government or law enforcement officials or private parties as, in the sole discretion of the administrators and technology support providers, if they believe necessary or appropriate to respond to claims and legal process, to protect their property and rights or a third party, to protect the safety of the public or any person, or to prevent or stop any illegal, unethical or legally actionable activity.
            Your information or data may also be provided to various tax authorities upon any demand or request from them. You acknowledge that SHIKSHAN AI can be accessed from anywhere in the world and it will have users from all over the world and therefore governments, judiciaries or law enforcement authorities in various parts of the world may have or assume jurisdiction over SHIKSHAN AI and SHIKSHAN AI may be subject to the laws, rules, regulations and judgments of various countries, states, municipalities or provinces where it may not have a direct presence to store, process, collect, use or keep your information or data. You acknowledge that government or law enforcement authorities in the countries where your data or information is stored may have the right to decrypt, collect, monitor or access your data or information, which actions are completely out of the control of the administrators and technology support providers of SHIKSHAN AI. The administrators and technology support providers of SHIKSHAN AI do not take any responsibility for such actions.
            Deleting your information
            If you wish to have the information or data that you have provided deleted, you can always do so by sending an email request to contact.justechai@gmail.com You may note that deletion of certain information or data may lead to cancellation of your registration with SHIKSHAN AI and your access to certain features of SHIKSHAN AI. You also agree and acknowledge that certain data or information cannot be deleted or may be prohibited to be deleted as required under any applicable law, law enforcement requests or under any judicial proceedings.
            Changes to this Privacy Policy
            SHIKSHAN AI reserves the right to modify this privacy statement at any time, so please review it frequently. If a material change is made to the practices regarding your personally identifiable information, you will be notified, by means of a notice on SHIKSHAN AI.
            How to contact us?
            If you have any queries, comments, or requests, please contact us by sending an email to contact.justechai@gmail.com 
            By visiting this page on our website: https://www.justech-ai.in/
            By mail: VOPA, 3rd Floor, Commerce Avenue, Paud Road, Kothrud, Pune, Maharashtra, India
          `}
          
          <h2>2. Information We Collect</h2>
          <p>More privacy policy content...</p>
          
          {/* Add more sections as needed */}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default PrivacyPolicy;